name: smart_scada
description: A mobile app for Smart SCADA alarm management and remote HMI view.
version: 1.0.0+1

environment:
  sdk: '^3.5.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  provider: ^6.1.0
  flutter_local_notifications: ^17.1.2
  http: ^1.2.1
  google_fonts: ^6.1.0
  shared_preferences: ^2.5.3
  intl: ^0.18.1
  fl_chart: ^0.66.2
  firebase_messaging: ^14.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_icon.png
    - assets/images/login_icon.png
    

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"